# -*- coding: utf-8 -*-
"""Find MMM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Iu0_BY96PQ6dfT2tfkKL4jUxVB2KWNL
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import numpy as np
import matplotlib .pyplot as plt
# %matplotlib inline

import statistics

#mean,median,mode
df=sns.load_dataset('tips')

df.head()

np.mean(df['total_bill'])

np.median(df['total_bill'])

statistics.mode(df['total_bill'])

sns.boxplot(df['total_bill'])

sns.histplot(df['total_bill'])



from inspect import Traceback
sns.histplot(df['total_bill'],kde=True)

df1=sns.load_dataset('iris')

df1.head()

sns.histplot(df1['sepal_length'],kde=True)

sns.histplot(df1['sepal_width'],kde=True)

sns.countplot(df1['species'])

np.percentile(df1['sepal_length'],[25,75])

